---
- name: Pull docker image of Calculator
  hosts: client1
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull vartikach02/miniproj_calculator

    - name: running container
      shell: docker run -it -d vartikach02/miniproj_calculator